# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a41fe154dd47a651c3557d7c5e54f02b0c52084de62bd86794741a5770c56b47a211fa8d93c237aca47f8c5e92dc950a31f0fa6b44b6691be61485507d38b7ba

test:
  secret_key_base: b818205374d4dd4bd98e9d52764bab1d71d2c3e6313c467a4b2c5f04f09d31a7ee23fbfe23f5e2be0e0a1fb68dba55d20f134b0e3384a3d2e19fa896ad0340ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
